### ISSUE TITLE
mip2核心文件和mip-nav-slidedown组件有兼容性。高度不能撑起来

### ISSUE THREAD

**Issue by tfciw** [mipengine/mip2-extensions#254]
**BUG 描述**
清晰和准确的描述 Bug 是什么

**复现步骤**
重新复现 Bug 的步骤

官网核心换位mip2后，该组件出现bug
https://www.mipengine.org/examples/mip-extensions/mip-nav-slidedown.html
点击预览，点击demo页按钮即可复现。高度撑不起来。并且头部会跟着滚动（期望固定）

**期望结果**
顶部固定。列表滚动。且列表页全屏
![image](https://user-images.githubusercontent.com/18052602/45015570-c134bb00-b054-11e8-931a-7d1ad6a1b6b6.png)

**bug截图**
![image](https://user-images.githubusercontent.com/18052602/45015453-56837f80-b054-11e8-9ce1-b9413dd9794c.png)

**环境及版本信息:**
 所有环境。
预估导致因素：mip2核心文件。组件8.27号还是正常的。应该是最近的核心文件改动导致。

**Comment by huanghuiquan** [comment]
**问题定位**

问题是由这个 PR 引入的
@xiaoiver https://github.com/mipengine/mip2/pull/228  

```css
body {
  overflow-y: auto;
  overflow-x: hidden; // bug
  position: relative;
  &.trigger-layout {
    height: 100% !important;
  }
}
```

当 body 不没撑满屏幕时，会导致下拉菜单被父元素的 overflow hidden 截断
